### ISSUE TITLE
知苗

### ISSUE THREAD

**Issue by mklzl** [sotowang/zmyy_seckill#1]
大佬，持续关注你的进度

**Comment by agarwoodd** [comment]
验证码给的字符串是图片的base64，需要转回去就能拿到图片，我遇到了zftsl 这个值计算的问题，可以交流交流

**Comment by mklzl** [comment]
> 验证码给的字符串是图片的base64，需要转回去就能拿到图片，我遇到了zftsl 这个值计算的问题，可以交流交流

你是需要计算得到session id还是什么？

**Comment by agarwoodd** [comment]
zftsl 这个参数好像最后提交验证用的

**Comment by mklzl** [comment]
> zftsl 这个参数好像最后提交验证用的

这个是不是经纬度，加ID，加上client的session id加上验证证书，然后tsl加密生成的

**Comment by qaz460472353** [comment]
创个群吧，众人拾柴火焰高

**Comment by agarwoodd** [comment]
可以 一起想办法

**Comment by agarwoodd** [comment]
> > zftsl 这个参数好像最后提交验证用的
> 
> 这个是不是经纬度，加ID，加上client的session id加上验证证书，然后tsl加密生成的

看小程序里写的 好像和时间有关系

**Comment by qaz460472353** [comment]
https://github.com/xjblszyy/JiuJia   可以参考下这个约苗秒杀的

**Comment by littleBK** [comment]
我也在看这个，之前知苗是没有滑块验证码的，现在加上了

**Comment by mklzl** [comment]
> https://github.com/xjblszyy/JiuJia 可以参考下这个约苗秒杀的

约苗的比较好弄，抓包获取cookie和tk就能跑起来，但是主要好像是针对成都的比较多

**Comment by agarwoodd** [comment]
> 我也在看这个，之前知苗是没有滑块验证码的，现在加上了

滑块验证码，可以用OpenCV 破解

**Comment by littleBK** [comment]
OpenCV？这块不是特别了解啊，有没有什么代码什么的可以推荐一下呢？而且这个项目是Go写的，OpenCV现在支持Go吗？

**Comment by sotowang** [comment]
> 验证码给的字符串是图片的base64，需要转回去就能拿到图片，我遇到了zftsl 这个值计算的问题，可以交流交流
我也遇到了这个问题

**Comment by Summer90xia** [comment]
持续关注中，加油

**Comment by iddddg** [comment]
同样想知道，拖拽验证码，怎么过

**Comment by iddddg** [comment]
方便给个联系方式嘛，或者拉个群啊

**Comment by sotowang** [comment]
> 方便给个联系方式嘛，或者拉个群啊

我建了个群，感兴趣的可以加一下  788512807
